@startuml
' Component diagram
title Diagram komponentov: Nástroj "I Know My Uni"

package "Diplomova-Praca" {
  component "ikmu.sh" as ikmu <<Main Bash>>

  package modules {
    component "brute-ais.py" as brute_ais <<Python>>
    component "brute-webmail.py" as brute_webmail <<Python>>
    component "scan-ports.sh" as scan_ports <<Bash>>
    component "http-headers.sh" as http_headers <<Bash>>
    component "tech-detect.sh" as tech_detect <<Bash>>
    component "find-pass.sh" as find_pass <<Bash>>
    component "gen-pass.sh" as gen_pass <<Bash>>
    component "ip-info.sh" as ip_info <<Bash>>
    component "ping-uni.sh" as ping_uni <<Bash>>
    component "tech-detect.py" as tech_detect_python <<Python>>
    component "mirror-web.sh" as mirror_web <<Bash>>
  }

  package extended {
    component "detect-round.sh" as detect_round <<Bash>>
  }

  package requirements {
    component "check_dependencies.sh" as check_dependencies <<Bash>>
    component "install.sh" as install <<Bash>>
    component "python.txt" as python <<Text File>>
    component "bash.txt" as bash <<Text File>>
  }
  
  package mirrors_full_localhost {
    component "login.html" as login_webmail_html <<HTML>>
    component "common.css" as common_css_webmail <<CSS>>
    component "capture.php" as capture_webmail <<PHP>>
    component "logo.PNG" as logo_webmail <<PNG>>
  }

  component "logs/" as logs <<Folder>>
  artifact "log_found_ais.txt" as log_found_ais <<Text File>>
  artifact "log_found_webmail.txt" as log_found_webmail <<Text File>>
  artifact "passwords.txt" as passwords <<Text File>>
  component "mirrors/" as mirrors <<Folder>>
  component "webmail_date_time/" as webmail_mirrors <<Folder>>
  component "ais_date_time/" as ais_mirrors <<Folder>>
  component "studentmail.ukf.sk/" as student_mail_ukf_sk <<Folder>>
  component "ais2.ukf.sk/" as ais2_ukf_sk <<Folder>>
  component "webmail/" as webmail <<Folder>>
  artifact "index.html" as webmail_index <<HTML>>
  component "ais/" as ais <<Folder>>
  component "portal/" as portal <<Folder>>
  artifact "start.do.html" as start_do_html <<HTML>>
  component "css/" as ais_css <<Folder>>
  component "images/" as ais_images <<Folder>>
  component "js/" as ais_js <<Folder>>
  artifact "bootstrap.min.css" as ais_bootstrap <<CSS>>
  artifact "portal_2_common.css" as ais_portal_common <<CSS>>
  artifact "portal_2.css" as ais_portal_2 <<CSS>>
  artifact "ais_web_images" as ais_all_images <<png,jpg,ico,gif>>
  artifact "jquer-3.2.1.min.js" as ais_jquery <<js>>
  artifact "portal_2.js" as ais_portal_js <<js>>
  artifact "http_headers_url_date_log.txt" as http_headers_url_date_log <<Text File>>
  artifact "ip_info_url_date_log.txt" as ip_info_url_date_log <<Text File>>
  artifact "tech_detect_url_date.txt" as tech_detect_url_date <<JSON>>
}

ikmu --> brute_ais
ikmu --> brute_webmail
ikmu --> scan_ports
ikmu --> http_headers
ikmu --> find_pass
ikmu --> gen_pass
ikmu --> ip_info
ikmu --> tech_detect
ikmu --> ping_uni
ikmu --> tech_detect_python
tech_detect --> detect_round
ikmu --> mirror_web

brute_ais ..> logs : Vytvorí a zapíše 
brute_webmail ..> logs : Vytvorí a zapíše 
logs ..> log_found_ais 
logs ..> log_found_webmail 
gen_pass ..> passwords : Vytvorí a zapíše 
mirror_web ..> mirrors
mirrors ..> webmail_mirrors
mirrors ..> ais_mirrors
webmail_mirrors ..> student_mail_ukf_sk
ais_mirrors ..> ais2_ukf_sk
student_mail_ukf_sk ..> webmail
webmail ..> webmail_index
ais2_ukf_sk ..> ais
ais ..> portal
ais ..> start_do_html
ais ..> ais_css
ais ..> ais_images
ais ..> ais_js
ais_css ..> ais_bootstrap
ais_css ..> ais_portal_common
ais_css ..> ais_portal_2
ais_images ..> ais_all_images
ais_js ..> ais_jquery
ais_js ..> ais_portal_js

modules ..> mirrors_full_localhost

ikmu --> requirements : Prvý krok 
check_dependencies ..> bash
check_dependencies ..> python

http_headers ..> logs : Vytvorí a zapíše 
logs ..> http_headers_url_date_log

ip_info ..> logs : Vytvorí a zapíše
logs ..> ip_info_url_date_log

tech_detect ..> logs : Vytvorí a zapíše
logs ..> tech_detect_url_date
@enduml