@startuml
title Sekvenčný diagram: Prehľadávanie hesla v súbre "passwords.txt"

participant "ikmu.sh\n(main)" as IKMU
participant "find-pass.sh\n(modul)" as Modul
participant "modules/passwords.txt\n(File)" as File
participant "stdout" as Console


IKMU -> Modul : spustenie nástroja a výber modulu
Modul -> File : hľadanie hesla "search"

alt  ! -f "$PASS_FILE" 
  Modul -> Console : súbor passwords.txt neexistuje
end

alt grep -Fxqi -- "$search" "$PASS_FILE"
  Modul -> Console : úspech, heslo nájdene (riadok:heslo)
end
Modul -> Console : heslo sa v zozname nenachádza

@enduml