@startuml
title Sekvenčný diagram: Generovanie číslených hesiel 

participant "ikmu.sh\n(main)" as IKMU
participant "gen-pass.sh\n(modul)" as Modul
participant "modules/passwords.txt\n(File)" as File
participant "stdout" as Console


IKMU -> Modul : spustenie nástroja a výber modulu
Modul -> File : prefix hesla (6 číslic)

alt ! "$prefix" =~ ^[0-9]{6}$
  File --> Modul : exception
  Modul -> Console : prefix musí obsahovať presne 6 číslic (0-9)
  Modul --> IKMU : návrat s chybou 
end

alt -f "$PASS_FILE" 
  Modul -> File : premezať súbor passwords.txt: y/n ?
end

Modul -> File : generate_passwords() 

Modul -> Console : generovanie dokončené
Modul -> Console : počet hesiel

@enduml
