@startuml
title Sekvenčný diagram: Kontrola hlavičiek

participant "ikmu.sh\n(main)" as IKMU
participant "http-headers.sh\n(modul)" as Modul
participant "HTTP target\n(URL)" as Target
participant "resources/headers.txt\n(URL)" as Headers
participant "stdout" as Console


IKMU -> Modul : spustenie nástroja a výber modulu
Modul -> Target : zvolenie UKF Webmail / AiS

Modul -> Target : check_headers() 

alt 
  Target --> Modul : exception
  Modul -> Console : nesprávna voľba
  Modul --> IKMU : návrat s chybou
end

Target -> Modul : získane hlavičky
Modul -> Headers : načítanie externých hlavičiek do zoznamu headers[]

loop header in "${headers[@]}"
  alt -n "$value"
    Modul -> Console : výpis nájdených hlavičiek podľa zoznamu a ukladanie výsledkov do logs/
  end
  Modul -> Console : výpis nenájdených hlavičiek podľa zoznamu a ukladanie výsledkov do logs/
end

@enduml